<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Auto;

class AutoNuevoSeeder extends Seeder
{
    public function run()
    {
        Auto::insert([
            [
                'marca' => 'Toyota',
                'modelo' => 'Camry',
                'año' => 2024,
                'precio' => 32000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'Sedán',
                'estado' => 'nuevo',
                'descripcion' => 'Toyota Camry 2024, lujo y tecnología avanzada.',
                'imagen_url' => 'images/Carros/toyotacamry.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Ford',
                'modelo' => 'Mustang',
                'año' => 2024,
                'precio' => 55000,
                'kilometraje' => 0,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Deportivo',
                'estado' => 'nuevo',
                'descripcion' => 'Ford Mustang 2024, potencia y diseño icónico.',
                'imagen_url' => 'images/Carros/fordmustang.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Tesla',
                'modelo' => 'Model 3',
                'año' => 2024,
                'precio' => 45000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Eléctrico',
                'tipo' => 'Sedán',
                'estado' => 'nuevo',
                'descripcion' => 'Tesla Model 3 2024, rendimiento y tecnología eléctrica.',
                'imagen_url' => 'images/Carros/teslamodel3.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Chevrolet',
                'modelo' => 'Silverado',
                'año' => 2024,
                'precio' => 60000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'Pickup',
                'estado' => 'nuevo',
                'descripcion' => 'Chevrolet Silverado 2024, la mejor camioneta para el trabajo pesado.',
                'imagen_url' => 'images/Carros/chevroletsilverado.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'BMW',
                'modelo' => 'X5',
                'año' => 2024,
                'precio' => 70000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'SUV',
                'estado' => 'nuevo',
                'descripcion' => 'BMW X5 2024, elegancia y rendimiento todoterreno.',
                'imagen_url' => 'images/Carros/bmwx5.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Audi',
                'modelo' => 'A4',
                'año' => 2024,
                'precio' => 42000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'Sedán',
                'estado' => 'nuevo',
                'descripcion' => 'Audi A4 2024, sofisticación y potencia en un solo auto.',
                'imagen_url' => 'images/Carros/audia4.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Hyundai',
                'modelo' => 'Tucson',
                'año' => 2024,
                'precio' => 35000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'SUV',
                'estado' => 'nuevo',
                'descripcion' => 'Hyundai Tucson 2024, seguridad y confort en cada viaje.',
                'imagen_url' => 'images/Carros/hyundaitucson.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Mercedes-Benz',
                'modelo' => 'C-Class',
                'año' => 2024,
                'precio' => 65000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'Sedán',
                'estado' => 'nuevo',
                'descripcion' => 'Mercedes-Benz C-Class 2024, lujo y tecnología en su máxima expresión.',
                'imagen_url' => 'images/Carros/mercedescclass.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Volkswagen',
                'modelo' => 'Tiguan',
                'año' => 2024,
                'precio' => 39000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'SUV',
                'estado' => 'nuevo',
                'descripcion' => 'Volkswagen Tiguan 2024, versatilidad y tecnología de última generación.',
                'imagen_url' => 'images/Carros/vwtiguan.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Honda',
                'modelo' => 'HR-V',
                'año' => 2024,
                'precio' => 31000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Gasolina',
                'tipo' => 'SUV',
                'estado' => 'nuevo',
                'descripcion' => 'Honda HR-V 2024, diseño innovador y eficiencia de combustible.',
                'imagen_url' => 'images/Carros/hondahrv.jpg',
                'disponible' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}