<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Moto;

class MotoSeeder extends Seeder
{
    public function run()
    {
        Moto::insert([
            [
                'marca' => 'Yamaha',
                'modelo' => 'YZF-R3',
                'año' => 2022,
                'precio' => 7500,
                'kilometraje' => 3000,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Deportiva',
                'descripcion' => 'Yamaha YZF-R3 2022, moto deportiva con gran rendimiento.',
                'imagen_url' => 'images/Motos/yamaha_r3.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Honda',
                'modelo' => 'CB500X',
                'año' => 2021,
                'precio' => 9000,
                'kilometraje' => 5000,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Adventure',
                'descripcion' => 'Honda CB500X 2021, perfecta para largos recorridos.',
                'imagen_url' => 'images/Motos/honda_cb500x.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Kawasaki',
                'modelo' => 'Ninja 400',
                'año' => 2023,
                'precio' => 8200,
                'kilometraje' => 0,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Deportiva',
                'descripcion' => 'Kawasaki Ninja 400 2023, potencia y estilo en una moto deportiva.',
                'imagen_url' => 'images/Motos/kawasaki_ninja400.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Ducati',
                'modelo' => 'Panigale V4',
                'año' => 2022,
                'precio' => 29000,
                'kilometraje' => 2000,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Superdeportiva',
                'descripcion' => 'Ducati Panigale V4 2022, una bestia en las pistas.',
                'imagen_url' => 'images/Motos/ducati_panigale_v4.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'BMW',
                'modelo' => 'R 1250 GS',
                'año' => 2021,
                'precio' => 18000,
                'kilometraje' => 8000,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Adventure',
                'descripcion' => 'BMW R 1250 GS 2021, diseñada para explorar cualquier terreno.',
                'imagen_url' => 'images/Motos/bmw_r1250gs.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Harley-Davidson',
                'modelo' => 'Iron 883',
                'año' => 2020,
                'precio' => 11000,
                'kilometraje' => 6000,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Cruiser',
                'descripcion' => 'Harley-Davidson Iron 883 2020, estilo clásico y robusto.',
                'imagen_url' => 'images/Motos/harley_iron883.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'KTM',
                'modelo' => 'Duke 390',
                'año' => 2022,
                'precio' => 7000,
                'kilometraje' => 2500,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Naked',
                'descripcion' => 'KTM Duke 390 2022, una naked ligera y agresiva.',
                'imagen_url' => 'images/Motos/ktm_duke390.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Suzuki',
                'modelo' => 'Hayabusa',
                'año' => 2023,
                'precio' => 25000,
                'kilometraje' => 500,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Superdeportiva',
                'descripcion' => 'Suzuki Hayabusa 2023, velocidad y potencia sin igual.',
                'imagen_url' => 'images/Motos/suzuki_hayabusa.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Triumph',
                'modelo' => 'Bonneville T120',
                'año' => 2021,
                'precio' => 13000,
                'kilometraje' => 4000,
                'transmision' => 'Manual',
                'combustible' => 'Gasolina',
                'tipo' => 'Clásica',
                'descripcion' => 'Triumph Bonneville T120 2021, un estilo clásico renovado.',
                'imagen_url' => 'images/Motos/triumph_bonneville_t120.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'marca' => 'Zero',
                'modelo' => 'SR/F',
                'año' => 2023,
                'precio' => 19000,
                'kilometraje' => 0,
                'transmision' => 'Automática',
                'combustible' => 'Eléctrico',
                'tipo' => 'Eléctrica',
                'descripcion' => 'Zero SR/F 2023, alto rendimiento en una moto eléctrica.',
                'imagen_url' => 'images/Motos/zero_srf.jpg',
                'disponible' => 1,
                'usuario_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}